static const char *petscmachineinfo = "\n"
"-----------------------------------------\n"
"Libraries compiled on 2026-01-09 20:53:04 on hina01.hpc.oregonstate.edu \n"
"Machine characteristics: Linux-5.14.0-362.8.1.el9_3.x86_64-x86_64-with-glibc2.34\n"
"Using PETSc directory: /fs1/home/ceoas/chenchon/pism/petsc-install\n"
"Using PETSc arch: \n"
"-----------------------------------------\n";
static const char *petsccompilerinfo = "\n"
"Using C compiler: /fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/bin/mpicc  -fPIC -Wall -Wwrite-strings -Wno-unknown-pragmas -Wno-lto-type-mismatch -Wno-stringop-overflow -fstack-protector -fvisibility=hidden -O3 -march=sandybridge  \n"
"Using Fortran compiler: /fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/bin/mpif90  -fPIC -Wall -ffree-line-length-none -ffree-line-length-0 -Wno-lto-type-mismatch -Wno-unused-dummy-argument -O3 -march=sandybridge    \n"
"-----------------------------------------\n";
static const char *petsccompilerflagsinfo = "\n"
"Using include paths: -I/fs1/home/ceoas/chenchon/pism/petsc-install/include -I/fs1/home/ceoas/chenchon/pism/local_stack/include -I/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/hdf5-1.14.3-p2dy6qz3shofau35b6ikibxqo6onthbm/include -I/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/zlib-ng-2.1.6-be2z2spal7uib5osqfouapstexwk5ckg/include -I/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/include\n"
"-----------------------------------------\n";
static const char *petsclinkerinfo = "\n"
"Using C linker: /fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/bin/mpicc\n"
"Using Fortran linker: /fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/bin/mpif90\n"
"Using libraries: -Wl,-rpath,/fs1/home/ceoas/chenchon/pism/petsc-install/lib -L/fs1/home/ceoas/chenchon/pism/petsc-install/lib -lpetsc -Wl,-rpath,/fs1/home/ceoas/chenchon/pism/petsc-install/lib -L/fs1/home/ceoas/chenchon/pism/petsc-install/lib -Wl,-rpath,/fs1/home/ceoas/chenchon/pism/local_stack/lib -L/fs1/home/ceoas/chenchon/pism/local_stack/lib -Wl,-rpath,/fs1/home/ceoas/chenchon/pism/local_stack/lib64 -L/fs1/home/ceoas/chenchon/pism/local_stack/lib64 -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/hdf5-1.14.3-p2dy6qz3shofau35b6ikibxqo6onthbm/lib -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/hdf5-1.14.3-p2dy6qz3shofau35b6ikibxqo6onthbm/lib -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/zlib-ng-2.1.6-be2z2spal7uib5osqfouapstexwk5ckg/lib -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/zlib-ng-2.1.6-be2z2spal7uib5osqfouapstexwk5ckg/lib -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/lib -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/openmpi-5.0.5-gpan6gdak7hjotoqee2umdghes7xfv2r/lib -Wl,-rpath,/fs1/local/cluster/CEOAS/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib64 -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib/gcc/x86_64-pc-linux-gnu/13.2.0 -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib/gcc/x86_64-pc-linux-gnu/13.2.0 -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib/gcc -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib/gcc -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib64 -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib64 -Wl,-rpath,/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib -L/fs1/local/ceoas/spack/opt/spack/linux-rocky9-sandybridge/gcc-13.2.0/gcc-13.2.0-kupqaiquixn5dpbdfjzn2ycm5ahnmurn/lib -lHYPRE -lfftw3_mpi -lfftw3 -lflapack -lfblas -lparmetis -lmetis -lnetcdf -lhdf5_hl -lhdf5 -lm -lz -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgfortran -lm -lgcc_s -lquadmath -lstdc++ -lquadmath\n"
"-----------------------------------------\n";
